### PR TITLE
downgrade to php 7.1

### PR DESCRIPTION
**Pull request by cspruiell**

### CODE REVIEW

**Comment by g105b** [comment]
Hello!

Looks like you're trying to make some changes to this repository. You're welcome to make suggestions and provide contributions.

What exactly are you trying to achieve? I'm happy to help you out with your first contribution.

Thanks,
Greg.

**Comment by cspruiell** [comment]
Sorry, this was meant to be against our forked repo. Please disregard.

**Comment by g105b** [comment]
No problem. If you have any questions, I'm happy to assist.

I am very interested to know how this repo is being used at Magento, would you be able to provide any information?

**Comment by cspruiell** [comment]
We're using it through phpgt/dom and just needed to make it compatible with PHP 7.1 since we still support that version.

**Comment by g105b** [comment]
Thanks for the info. I'm going to have a look at what PHP version requirements are set across PHP.Gt

Have a nice day!

**Pull request closed without merging**
