### PR TITLE
Match attribute names in a case-insensitive manner.

### PR DESCRIPTION
**Pull request by chrishow**
Modifies Translator to perform case-insensitive matches on attribute names.

eg:

Given `<div data-FOO='bar'>baz</div>`, both these selectors match:
` "[data-FOO='bar']"`
` "[data-foo='bar']"`

Case-sensitivity is maintained for attribute values, such that these selectors do not match:
` "[data-FOO='BAR']"`
` "[data-foo='BAR']"`

### CODE REVIEW

**Comment by g105b** [comment]
Hi @chrishow thank you for your first contribution to the repository. Nice to meet you!

I've just reviewed this PR and I'm happy with it. It all looks good to me. Have you intentionally marked is as WIP? Do you intend to add anything to this, or are you happy for it to be merged?

I see that the current version of PHPUnit only runs with PHP 8.1 or higher, so I suggest we update the Github Action runner to use the same PHPUnit as composer.json. I will do this, and while I'm at it I will implement matrix builds to test on all available PHP versions (this involves upgrading the Action runner to a new version of PHP Unit that I also maintain).

**Comment by g105b** [comment]
I've just updated the CI workflow to run all versions of PHP. I'm happy to merge if you are - just confirming because of the draft status you added to the PR.

**Comment by chrishow** [comment]
Hi!

I marked it as draft because this would break case-sensitive matching in XML. 

Have a look at issue #220 and let me know what you think over there...

**Comment by g105b** [comment]
I actually think it would be worth merging this PR first, and then implementing the distinction of XML vs HTML as a separate PR afterwards, because the use case for HTMLDocuments is so much more common than working with XML (at least for me). I'd like to hear your thoughts on this @chrishow .

**Comment by chrishow** [comment]
I agree that HTML-style matching is likely to be a much more common use case for this library. That's certainly the only way I'm using it...

So I have added an option to the constructor (`bool $htmlMode`) which defaults to true. If this is true, attribute names are matched in a case-insensitive manner. 

I've also added tests for `$htmlMode = false` (ie, 'XML mode'). 

So to continue using `Translator` for HTML-style matching, no changes to existing code are required, but to match XML-style, an extra argument is needed, eg:

Ordered argument style:
`new Translator("[data-FOO='bar']", ".//", false);`

Named argument style: 
`new Translator("[data-FOO='bar']", htmlMode: false);`

It's perhaps worth noting that for XML-style matching to work, you must load the document content with `DOMDocument->load`/`DOMDocument->loadXML` instead of `DOMDocument->loadHTMLFile`/`DOMDocument->loadHTML`, as the HTML loading methods automatically convert the tags and attribute names to lowercase.

**Comment by g105b** [comment]
I've just upgraded the minimum PHP version from 7.3 to 8.0 - even though 8.0 is out of date now, it's always a good idea to support as far back as possible. This change was necessary to utilise promoted constructor properties.

I will now run the unit tests on the [PHP.Gt/Dom](https://www.php.gt/dom) project, which heavily utilises this CssXPath library, to ensure no functionality has regressed.

**Comment by g105b** [comment]
Looks great:

https://github.com/PhpGt/Dom/actions/runs/7400933221

No issues with running your changes in PHP.Gt/Dom

I'll go ahead and merge.

**Comment by g105b** [comment]
Thanks so much for your first contribution!

**Pull request merged**
